### ISSUE TITLE
Comparison with Lit?

### ISSUE THREAD

**Issue by Brian-McBride** [nativew/nativeweb#1]
Your lib seems a lot like the popular `lit`.  https://lit.dev/

I would be super interested in a comparison chart. What do I lose between Nativeweb's 1k and Lit's 5k in size?

**Comment by hum-n** [comment]
Hey, the goal of Native Web is to be the smallest viable library.

The biggest difference is that Lit is reactive. It works a bit like React and Vue in that components automatically rerender on state changes. That's a big chunk of the weight added.

I believe that for most websites, it's not necessary. You can easily live by manually updating the dom with scoped `@query` selectors or watch for `attributeChanged()`. For the small updates you'll need to make.

If you're building an app where many things need to be updated on state changes, Lit is a better choice.

Now other than that, most big features are similar with some syntax differences. You'll have more options to tweak with Lit, but Native Web is simpler and less verbose.

One thing that is implemented differently is events. I think Native Web does it better, but of course, I'm biased.

## Events

### Component
`Lit`
```js
constructor() {
    super();
    this.addEventListener('click', (e) => this.onClick(e));
}
```
`Native Web`
```js
@event() click = this.onClick();
```

### Child
`Lit`
```js
protected render() {
    return html`
        <button @click="${this.close}">X</button>
        <h2 @click="${this.change}">Title</h2>
        <button @click="${this.close}">Close</button>
    `;
}
```
`Native Web`
```js
@event() click = {
    '@close': this.close(),
    '@change': this.change()
};

render() {
    return `
        <button @close>X</button>
        <h2 @change>Title</h2>
        <button @close>Close</button>
    `;
}
```

### External
`Lit`
```js
const readyEvent = new CustomEvent('other-component.ready', {
    detail: {
        message: "Ready 🚀"
    }
});
dispatchEvent(readyEvent);
```
```js
constructor() {
    super();
    window.addEventListener('other-component.ready', this.onReady);
}
```
`Native Web`
```js
@customEvent() ready = 'Ready 🚀';
dispatchEvent(this.ready);

```
```js
@event() ready = {
    'other-component': this.onReady()
};
```
